#ifndef _SIMULA_MOLECULE_TYPE_DEFINE_
#define _SIMULA_MOLECULE_TYPE_DEFINE_

#include "global.h"

namespace simula {

	struct simOneBond {	
		simF1 energy;
		simI1 target;
		std::vector<simI3> rpos;
	};

	typedef std::vector<simOneBond> simBonds;

	/**
	 * @brief Store molecule type information
	 * @var name
	 * @var amount
	 * @var gen_id
	 * @var usr_id
	 * @var size
	 * @var rpos (with id)
	 */
	class Molecule_Type {
	private:
		simString _name_; //< type name in string
		simBonds  _bond_; //< bonding definition
		simI1  _amount_;  //< total amount of molecule will be created
		simI1  _gen_idx_; //< data index determined by the program (count from 1)
		simI1  _usr_idx_; //< type index defined by user
		simVI2 _dot_pos_; //< relative position of components
		simVI1 _dot_idx_; //< relative indices of components
	public:

		/**
		 * @defgroup Getters
		 * @{
		 */
		/** @brief get type name in string */
		inline const simString name() const { return _name_; }
		/** @brief get type total amount */
		inline const simI1   amount() const { return _amount_; }
		/** @brief get type reference index defined by user */
		inline const simI1  usr_id() const { return _usr_idx_; }
		/** @brief get type index generated by program */
		inline const simI1  gen_id() const { return _gen_idx_; }
		/** @brief get total number of components (dots) */
		inline const simSize size() const { return _dot_pos_.size(); }
		/** @brief get vector containing component point positions */
		inline const simVI2& rpos() const { return _dot_pos_; }
		/** @brief get vector containing component point indices */
		inline const simVI1& ridx() const { return _dot_idx_; }
		/** @} */

		/**
		 * @defgroup Setters
		 * @{
		 */
		/** @brief set type name **/
		void set_name(const simString& name);
		/** @brief set type index **/
		void set_gen_id(const simI1 id);
		/** @brief set type index **/
		void set_usr_id(const simI1 id);
		/** @brief set type amount **/
		void set_amount(const simI1 am);
		/** @brief set relative component position with a list of integer pairs **/
		void set_rpos(const simVI2& rpos, const simVI1& ridx);
		void set_rpos(const simI1 sz, const simI1* ls);
		void set_bond(const std::vector<simOneBond>& bonds);
		/** @} */

#ifndef NDEBUG
		/** @brief debug function **/
		void debug();
#endif

	};
};

#endif // _SIMULA_MOLECULE_TYPE_DEFINE_
